services:
  order_service:
    build:
      context: .
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - aiti
    depends_on:
      aiti_db:
        condition: service_healthy
    restart: "always"
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "postgresql://aiti:aiti@aiti_db:5432/aiti"
  aiti_db:
    image: postgres:18
    container_name: aiti_db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U aiti" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - aiti
    restart: "always"
    environment:
      TZ: 'Europe/Moscow'
      PGTZ: 'Europe/Moscow'
      POSTGRES_HOST_AUTH_METHOD: 'trust'
      POSTGRES_PASSWORD: aiti
      POSTGRES_USER: aiti
    ports:
      - "5433:5432"
networks:
  aiti: